title: Slate theme
description: Slate is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-slate

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Welcome to Marcelo Fuentes' site]
description: [This site has some of Marcelo's Projects & Consulting Work]

# github:
#   zip_url: http://example.com/download.zip
#   another_url: another value
