title: Slate theme
description: Slate is a theme for GitHub Pages.
theme: jekyll-theme-slate

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Welcome to Marcelo Fuentes' site]
description: [This site has some of Marcelo's Projects & Consulting Work]
